name: "[M] Link to session minutes"

on:
  workflow_dispatch:
    inputs:
      sessionNumber:
        description: 'Session issue number or "all" to link all possible minutes'
        required: true
        default: 'all'
        type: string

jobs:
  add-minutes:
    name: Link to session minutes
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout latest version of release script
        uses: actions/checkout@v4
        with:
          ref: main

      # Note: no "package-lock.json" and no "npm ci" on purpose to retrieve
      # latest version of w3c/tpac-breakouts tools (which are unversioned)
      - name: Install dependencies
        run: npm install

      - name: Link to session minutes
        run: npx add-minutes ${{ inputs.sessionNumber }}
        env:
          # A valid Personal Access Token (classic version) with project
          # and public_repo scope.
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
