name: "[M] View current schedule"

on:
  workflow_dispatch:

jobs:
  view-event:
    name: View the current schedule
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout latest version of release script
        uses: actions/checkout@v4
        with:
          ref: main

      # Note: no "package-lock.json" and no "npm ci" on purpose to retrieve
      # latest version of w3c/tpac-breakouts tools (which are unversioned)
      - name: Install dependencies
        run: npm install

      - name: Create directory to store result
        run: mkdir .schedule

      - name: Generate the HTML page
        run: npx tpac-breakouts view --format html > .schedule/index.html
        env:
          # Same valid Personal Access Token (classic version) as above, with
          # project and public_repo scope.
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
          GH_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}

      - name: Create ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: schedule
          path: .schedule
